### PR TITLE
Add missing files to ppc64le sysroot

### PR DESCRIPTION
**Pull request by bkuschel**
Required for dynamic linking of the `libcrypt.so` and `libsso.so` libraries for upcoming openssl support.

### CODE REVIEW

**Review by alexey-milovidov — APPROVED** [review]

**Comment by tavplubix** [comment]
Are we okay with adding binary files from unknown sources? Even if we are not going to use these files for official builds it still looks dangerous. cc: @santrancisco

**Comment by alexey-milovidov** [comment]
Yes, if they are byte-identical to the files from the official OS image.

**Comment by tavplubix** [comment]
If they are byte-identical to the files from the official OS image then the source is known :)
I mean that it's not obvious from the description of PRs like this. And it's easy to forget to compare the files before merging.

**Comment by santrancisco** [comment]
> I mean that it's not obvious from the description of PRs like this

100% this.. and it really is not obvious.. for example these 2 files, i downloaded and just spent an hour to see if i can track it down but searching for the hash (md5,sha1,sha256)- no result ... Sure, virus total is clean but as we all know, AV scanner does lousy job with signature base and for a library, dynamic, realtime analyser won't yield any result.  This is, of course, nothing against @bkuschel and looking at his track record, I feel super thankful for his contributions and there is always that trust we want to keep among opensource maintainers & contributors. 

>  if they are byte-identical to the files from the official OS image.

Absolutely, So perhaps we can make a new rule for contributing binary file such as this is to at least point out the exact version of the library & pointing out the exact .deb / .rpm file from which official distro + repository that one can download and validate? every distro will have their own compiled version and as we all know, even one byte is different, the final hash is different. 

For this particular example, unfortunately, I have tried to looked for the compiled version  (in debian and ubuntu) but had little luck. When running `strings crtbeginS.o` , i got "GCC: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4" which at least give me the version of GCC used to compile on quite an old version of ubuntu and already past its end of life.

**Comment by santrancisco** [comment]
Well.. my bad... clearly I need to Read The F**** Manual :) .. (just saw this in the readme.md for this repository:)

CleanShot 2022-12-09 at 22 22 37

And after downloading the docker image and checking it.. sure enough..

CleanShot 2022-12-09 at 22 25 49@2x

I can help checking it in the future if needed since the steps already lay out.

**Pull request merged**
